language: android

sudo: false

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.0
  - android-23
  - extra-android-m2repository
  - extra-android-support
  licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew
script:
  - ./gradlew assembleRelease
